version: '2'

services:
 web:
   build: pushstock-app
   ports:
     - "4200:4200"
     - "80:80"
   links:
     - database
   depends_on:
     - database
   command: ["./wait-for-it.sh", "database:27017", "--strict", "--", "./wait-for-mongo.sh"]

 database:
   build: database
   image: mongo
   volumes:
     - /tmp/mongodb:/data/db
   ports:
     - "27017:27017"
