version: '2'

services:
 web:
   build: .
   ports:
     - "4200:4200"
   links:
     - database
   depends_on:
     - database
   command: ["./wait-for-it.sh", "database:27017", "--strict", "--", "./wait-for-mongo.sh"]

 database:
   image: mongo
   ports:
     - "27017:27017"
