version: '2'

services:
 web:
   build: .
   ports:
     - "4200:4200"
   links:
     - database
   depends_on:
     - database
   command: ["./wait-for-it.sh", "-h", "localhost", "-p", "27017"]
   volumes:
     - ./public/src:/usr/src/app/src

 database:
   image: mongo
   ports:
     - "27017:27017"
