version: '2'

services:
 angular:
   build: angular-client
   ports:
     - "4200:4200"

 express:
   build: express-server
   ports:
     - "3000:3000"
   links:
     - database

 database:
   image: mongo
   ports:
     - "27017:27017"
