# Create image based on latest mongo image
FROM mongo:latest 

# Get all the code needed to run the app
COPY . /
# Run script on container start to create users
#ENTRYPOINT ["./mongo-init-config.sh"]
